routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'guest'], function () {
    Route::get('/', 'AdminController@login')->name('login');
});
Route::group(['middleware' => 'auth'], function () {
    Route::group(['prefix' => 'home'], function () {
        Route::get('/', 'AdminController@index')->name('admin.home');
        Route::get('/alliance', 'AdminController@alliance')->name('admin.alliance');
        Route::get('/footer', 'AdminController@footer')->name('admin.footer');
        Route::get('/event', 'AdminController@event')->name('event.banner');
        Route::get('/service', 'AdminController@service')->name('service.banner');
        Route::get('/header', 'AdminController@header')->name('admin.header');
        Route::get('/descriptive', 'AdminController@descriptive')->name('admin.descriptive');
        Route::post('/header', 'AdminController@postHeader')->name('admin.header.store');
        Route::post('/footer', 'AdminController@postFooter');
        Route::post('/event', 'AdminController@postEvent');
        Route::post('/service', 'AdminController@postService');
        Route::post('/descriptive', 'AdminController@postDescriptive')->name('admin.descriptive.store');
    });

    Route::group(['prefix' => 'table'], function () {
        Route::get('brand', 'BrandController@getList');
        Route::get('category', 'CategoryController@getList');
        Route::get('certificate', 'CertificateController@getList');
        Route::get('corporation', 'CorporationController@getList');
        Route::get('event', 'EventController@getList');
        Route::get('headquarter', 'HeadquarterController@getList');
        Route::get('how-contact', 'HowContactController@getList');
        Route::get('type', 'ProductTypeController@getList');
        Route::get('product', 'ProductController@getList');
        Route::get('service', 'ServiceController@getList');
        Route::get('slider', 'SliderController@getList');
        Route::get('specialization', 'SpecializationController@getList');
        Route::get('seo', 'SeoController@listData');
        Route::get('post', 'PostController@listData');
        Route::get('newsletter', 'NewsletterController@listData');
    });

    Route::group(['prefix' => 'reorder'], function () {
        Route::post('brand', 'BrandController@reorder');
        Route::post('category', 'CategoryController@reorder');
        Route::post('certificate', 'CertificateController@reorder');
        Route::post('corporation', 'CorporationController@reorder');
        Route::post('event', 'EventController@reorder');
        Route::post('headquarter', 'HeadquarterController@reorder');
        Route::post('how-contact', 'HowContactController@reorder');
        Route::post('type', 'ProductTypeController@reorder');
        Route::post('product', 'ProductController@reorder');
        Route::post('service', 'ServiceController@reorder');
        Route::post('slider', 'SliderController@reorder');
        Route::post('specialization', 'SpecializationController@reorder');
        Route::post('post', 'PostController@reorder');
    });


    Route::resource('brand', 'BrandController');
    Route::resource('category', 'CategoryController');
    Route::resource('certificate', 'CertificateController');
    Route::resource('corporation', 'CorporationController');
    Route::get('contact/download', 'ContactController@download')->name('contact.download');
    Route::resource('contact', 'ContactController');
    Route::resource('event', 'EventController');
    Route::resource('how-contact', 'HowContactController');
    Route::resource('product/detail', 'ProductDetailController');
    Route::resource('product/type', 'ProductTypeController');
    Route::resource('product', 'ProductController');
    Route::resource('profile', 'ProfileController');
    Route::resource('role', 'RoleController');
    Route::resource('service', 'ServiceController');
    Route::resource('second-slider', 'SecondSliderController');
    Route::post('slider/text-general', 'SliderController@textGeneralUpdate')->name('slider.text.general');
    Route::resource('slider', 'SliderController');
    Route::resource('specialization', 'SpecializationController');
    Route::resource('headquarter', 'HeadquarterController');
    Route::resource('user', 'UserController');
    Route::get('seo/section', 'SeoController@sectionData');
    Route::resource('seo', 'SeoController');
    Route::get('post/{id}/comments', 'PostController@comments')->name('post.comments');
    Route::resource('post', 'PostController');
    Route::get('comment/{id}', 'PostController@comment')->name('comment.show');
    Route::delete('comment/{id}', 'PostController@commentDelete')->name('comment.destroy');

    Route::get('newsletter/{id}/send', 'NewsletterController@send');
    Route::get('newsletter/{id}/preview', 'NewsletterController@preview');
    Route::resource('newsletter', 'NewsletterController');

    Route::group(['prefix' => 'us'], function () {
        Route::get('/enterprise', 'UsController@enterprise')->name('us.enterprise');
        Route::get('/mission', 'UsController@mission')->name('us.mission');
        Route::get('/vision', 'UsController@vision')->name('us.vision');
        Route::get('/holding', 'UsController@holding')->name('us.holding');
        Route::get('/policy', 'UsController@policy')->name('us.policy');
        Route::get('/history', 'UsController@history')->name('us.history');
        Route::post('/enterprise', 'UsController@storeEnterprise');
        Route::post('/holding', 'UsController@storeHolding');
        Route::post('/{type}', 'UsController@store')->name('us.store');
    });

    //Routes to Galleries
    Route::post('/gallery/{id}/update', 'GalleryController@update')->name('gallery.update');
    Route::post('/gallery/{type}', 'GalleryController@uploadImagesByType');
    Route::delete('/gallery/{type}/{id}', 'GalleryController@deleteByType');
    Route::post('/pdf/{type}', 'GalleryController@uploadPDFByType');

    //Routes to Images
    Route::post('images/uploader', 'ImageController@postUploader')->name('images.uploader');
});

routes/front.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontController@index')->name('front.home');
Route::get('about', 'FrontController@about')->name('front.about');
Route::get('contact', 'FrontController@contact')->name('front.contact');
Route::get('events', 'FrontController@events')->name('front.events');
Route::get('event-detail', 'FrontController@event_detail')->name('front.event_detail');
Route::get('services', 'FrontController@services')->name('front.services');
Route::get('products', 'FrontController@products')->name('front.products');
Route::get('product-detail', 'FrontController@product_detail')->name('front.product_detail');
Route::get('product-filter', 'FrontController@product_filter')->name('front.product_filter');
Route::get('category', 'FrontController@category')->name('front.category');
Route::get('error-404', 'FrontController@error_404')->name('front.error_404');
Route::get('politics', 'FrontController@politics')->name('front.politics');
Route::get('certifications', 'FrontController@certifications')->name('front.certifications');
Route::get('search', 'FrontController@search')->name('front.search');
Route::get('no-product', 'FrontController@no_product')->name('front.no_product');
Route::get('thanks', 'FrontController@thanks')->name('front.thanks');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('chat/download', 'Admin\ChatController@download')->name('chat.download');

Route::namespace('Web')->group(function () {
    Route::get('/proximamente', 'WebController@coming')->name('web.coming');

    Route::get('/', 'WebController@index')->name('web.home');
    Route::get('nosotros', 'WebController@about')->name('web.about');
    Route::get('contacto', 'ContactController@index')->name('web.contact');

    Route::get('contacto/gracias', 'WebController@thanks')->name('web.contact.thanks');
    Route::get('eventos', 'WebController@events')->name('web.events.index');
    Route::post('eventos/loadmore', 'WebController@event_ajax')->name('web.events.load');
    Route::get('evento/{slug}', 'WebController@eventDetail')->name('web.events.show');
    Route::get('servicios', 'WebController@services')->name('web.services.index');
    Route::get('productos', 'ProductController@index')->name('web.products');
    Route::get('producto/buscar', 'WebController@product_filter')->name('web.product_filter');
    Route::get('producto/{slug?}', 'WebController@product_detail')->name('web.product_detail');
    Route::get('categoria', 'WebController@category')->name('web.category');
    Route::get('politicas', 'WebController@politics')->name('web.politics');
    Route::get('historia', 'WebController@history')->name('web.history');
    Route::get('certificaciones', 'WebController@certifications')->name('web.certifications');
    Route::post('category-products', 'ProductController@moreProductForCategory');
    Route::get('blogs', 'WebController@posts')->name('web.posts');
    Route::get('blog/{slug}', 'WebController@post')->name('web.post');
    Route::post('comment/{post}', 'CommentController@store')->name('web.comment.store');
    Route::post('more-comment', 'CommentController@more')->name('web.comment.more');
});


Route::post('/login', 'Auth\LoginController@login')->name('login.verify');
Route::group(['middleware' => 'auth'], function () {
    Route::get('/logout', 'Auth\LoginController@logout');
});

Route::get('newsletter', function () {
    $data['newsletter'] = \App\Models\Newsletter::find(1);
    return view('mailings.newsletter', $data);
});

app/Models/Service.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Service extends Model
{
    use SoftDeletes;
    protected $table = 'services';
    protected $dates = ['created_at', 'updated_at', 'deleted_at'];
    protected $hidden = ['created_at', 'updated_at', 'deleted_at'];
    protected $fillable = ['title', 'description', 'detail', 'gallery_id', 'reading_order'];
    public $timestamps = true;

    public function image()
    {
        return $this->belongsTo(Gallery::class, 'gallery_id');
    }
}

app/Http/Controllers/API/ServiceController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Resources\BannerResource;
use App\Http\Resources\ServiceResource;
use App\Models\SubTable;
use App\Services\Eloquent\Eloquent\ServiceService;

class ServiceController extends Controller
{
    /**
     * Banner
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function banner()
    {
        $data = SubTable::getServiceBanner();
        return $this->responseSuccess('', BannerResource::collection($data));
    }

    /**
     * Display a listing of the resource.
     *
     * @param ServiceService $serviceService
     * @return \Illuminate\Http\JsonResponse
     */
    public function index(ServiceService $serviceService)
    {
        $data = $serviceService->getAll();
        return $this->responseSuccess('', ServiceResource::collection($data));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/views/service/create.blade.php
@extends('admin.layout.base')

@section('bodyId')id="service"@endsection

@section('content')
    <section class="wrapper">
        <form action="{{ url('/admin/service') }}" method="POST" enctype="multipart/form-data">
            {{ csrf_field() }}
            <div class="row">
                <div class="col-sm-12">
                    <div class="panel">
                        <header class="panel-heading">Nuevo Servicio</header>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-8">
                    <div class="panel">
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="row">
                                        <div class="col-xs-12 col-md-12">
                                            <div class="form-group">
                                                <label>Título</label>
                                                <input class="form-control m-bot15" type="text" name="title">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-xs-12">
                                            <div class="form-group">
                                                <label>Descripción</label>
                                                <textarea name="description"
                                                          class="ckeditor form-control m-bot15"></textarea>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-xs-12">
                                            <div class="form-group">
                                                <label>Detalle</label>
                                                <textarea name="detail"
                                                          class="ckeditor form-control m-bot15"></textarea>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-sm-4">
                    <div class="panel">
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="row">
                                        <div class="col-xs-6">
                                            <a href="{{ url('/admin/service') }}"
                                               class="btn btn-danger btn-block">Cancelar</a>
                                        </div>
                                        <div class="col-xs-6">
                                            <button class="btn btn-success btn-block">Guardar</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="panel">
                        <header class="panel-heading">Imagen</header>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-xs-12">
                                    <div>
                                        @component('admin.partials.upload-image')
                                            @slot('title')Las imágenes deben de medir 1080x780 px @endslot
                                            @slot('inputName')image @endslot
                                        @endcomponent
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </section>
    @include('admin.partials.modals.cropper_image')
@endsection

@section('js')
    <script type="text/javascript" src="{{ asset('js/vendor/cropper.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/vendor/jquery-cropper.min.js') }}"></script>

    <script type="text/javascript" src="{{ asset('js/vendor/ckeditor/ckeditor.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/vendor/toastr.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/scripts/form.js') }}"></script>
    <script>
        Form.form('form', true);
        Form.imageEditor('#cropper_modal', '.fileupload', '#image_cropper', '.modal-btn-confirm', '#input_image', 1080, 780);
    </script>
@endsection

resources/views/admin/views/service/index.blade.php
@extends('admin.layout.base')

@section('bodyId')id="service"@endsection

@section('content')
    <section class="wrapper">
        <!-- page start-->
        <div class="row">
            <div class="col-sm-12">
                <section class="panel">
                    <header class="panel-heading">Servicios
                        <a href="{{ route('service.create') }}" class="pull-right btn btn-success">Nuevo
                            <i class="fa fa-plus"></i></a>
                    </header>

                    <div class="panel-body">
                        <div class="adv-table">
                            <table class="display table table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th style="width: 60px;">Orden</th>
                                    <th>Nombre</th>
                                    <th class="text-center" style="width: 20%">Acciones</th>
                                </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </section>

    @component('admin.partials.modals.delete')
        @slot('title') Eliminar servicio @endslot
        @slot('message') Seguro de eliminar el servicio : @endslot
    @endcomponent

@endsection

@section('js')
    <script type="text/javascript" src="{{ asset('js/vendor/toastr.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/scripts/form.js') }}"></script>
    <script>
        Form.form('form');
    </script>
@endsection

resources/views/admin/views/service/update.blade.php
@extends('admin.layout.base')

@section('bodyId')id="service"@endsection

@section('content')
    <section class="wrapper">
        <form action="{{ url('/admin/service/'.$service->id) }}" method="POST" enctype="multipart/form-data">
            {{ csrf_field() }}
            {{ method_field('PATCH') }}
            <div class="row">
                <div class="col-sm-12">
                    <div class="panel">
                        <header class="panel-heading">Editar servicio</header>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-8">
                    <div class="panel">
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="row">
                                        <div class="col-xs-12 col-md-12">
                                            <div class="form-group">
                                                <label>Título</label>
                                                <input class="form-control m-bot15" type="text" name="title"
                                                       value="{{ $service->title }}">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-xs-12">
                                            <div class="form-group">
                                                <label>Descripción</label>
                                                <textarea name="description"
                                                          class="ckeditor form-control m-bot15">{{ $service->description }}</textarea>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-xs-12">
                                            <div class="form-group">
                                                <label>Detalle</label>
                                                <textarea name="detail"
                                                          class="ckeditor form-control m-bot15">{{ $service->detail }}</textarea>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-sm-4">
                    <div class="panel">
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="row">
                                        <div class="col-xs-6">
                                            <a href="{{ route('service.index') }}"
                                               class="btn btn-danger btn-block">Cancelar</a>
                                        </div>
                                        <div class="col-xs-6">
                                            <button class="btn btn-success btn-block">Guardar</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="panel">
                        <header class="panel-heading">Imagen</header>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-xs-12">
                                    <div>
                                        @component('admin.partials.upload-image', ['path' => isset($service->image) ? $service->image->path : ''])
                                            @slot('title')@endslot
                                            @slot('inputName') image @endslot
                                        @endcomponent
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </section>
    @include('admin.partials.modals.cropper_image')
@endsection

@section('js')
    <script type="text/javascript" src="{{ asset('js/vendor/cropper.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/vendor/jquery-cropper.min.js') }}"></script>

    <script type="text/javascript" src="{{ asset('js/vendor/ckeditor/ckeditor.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/vendor/toastr.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/scripts/form.js') }}"></script>
    <script>
        Form.form('form', true);
        Form.imageEditor('#cropper_modal', '.fileupload', '#image_cropper', '.modal-btn-confirm', '#input_image', 1080, 780);
    </script>
@endsection