routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'guest'], function () {
    Route::get('/', 'AdminController@login')->name('login');
});
Route::group(['middleware' => 'auth'], function () {
    Route::group(['prefix' => 'home'], function () {
        Route::get('/', 'AdminController@index')->name('admin.home');
        Route::get('/alliance', 'AdminController@alliance')->name('admin.alliance');
        Route::get('/footer', 'AdminController@footer')->name('admin.footer');
        Route::get('/event', 'AdminController@event')->name('event.banner');
        Route::get('/service', 'AdminController@service')->name('service.banner');
        Route::get('/header', 'AdminController@header')->name('admin.header');
        Route::get('/descriptive', 'AdminController@descriptive')->name('admin.descriptive');
        Route::post('/header', 'AdminController@postHeader')->name('admin.header.store');
        Route::post('/footer', 'AdminController@postFooter');
        Route::post('/event', 'AdminController@postEvent');
        Route::post('/service', 'AdminController@postService');
        Route::post('/descriptive', 'AdminController@postDescriptive')->name('admin.descriptive.store');
    });

    Route::group(['prefix' => 'table'], function () {
        Route::get('brand', 'BrandController@getList');
        Route::get('category', 'CategoryController@getList');
        Route::get('certificate', 'CertificateController@getList');
        Route::get('corporation', 'CorporationController@getList');
        Route::get('event', 'EventController@getList');
        Route::get('headquarter', 'HeadquarterController@getList');
        Route::get('how-contact', 'HowContactController@getList');
        Route::get('type', 'ProductTypeController@getList');
        Route::get('product', 'ProductController@getList');
        Route::get('service', 'ServiceController@getList');
        Route::get('slider', 'SliderController@getList');
        Route::get('specialization', 'SpecializationController@getList');
        Route::get('seo', 'SeoController@listData');
        Route::get('post', 'PostController@listData');
        Route::get('newsletter', 'NewsletterController@listData');
    });

    Route::group(['prefix' => 'reorder'], function () {
        Route::post('brand', 'BrandController@reorder');
        Route::post('category', 'CategoryController@reorder');
        Route::post('certificate', 'CertificateController@reorder');
        Route::post('corporation', 'CorporationController@reorder');
        Route::post('event', 'EventController@reorder');
        Route::post('headquarter', 'HeadquarterController@reorder');
        Route::post('how-contact', 'HowContactController@reorder');
        Route::post('type', 'ProductTypeController@reorder');
        Route::post('product', 'ProductController@reorder');
        Route::post('service', 'ServiceController@reorder');
        Route::post('slider', 'SliderController@reorder');
        Route::post('specialization', 'SpecializationController@reorder');
        Route::post('post', 'PostController@reorder');
    });


    Route::resource('brand', 'BrandController');
    Route::resource('category', 'CategoryController');
    Route::resource('certificate', 'CertificateController');
    Route::resource('corporation', 'CorporationController');
    Route::get('contact/download', 'ContactController@download')->name('contact.download');
    Route::resource('contact', 'ContactController');
    Route::resource('event', 'EventController');
    Route::resource('how-contact', 'HowContactController');
    Route::resource('product/detail', 'ProductDetailController');
    Route::resource('product/type', 'ProductTypeController');
    Route::resource('product', 'ProductController');
    Route::resource('profile', 'ProfileController');
    Route::resource('role', 'RoleController');
    Route::resource('service', 'ServiceController');
    Route::resource('second-slider', 'SecondSliderController');
    Route::post('slider/text-general', 'SliderController@textGeneralUpdate')->name('slider.text.general');
    Route::resource('slider', 'SliderController');
    Route::resource('specialization', 'SpecializationController');
    Route::resource('headquarter', 'HeadquarterController');
    Route::resource('user', 'UserController');
    Route::get('seo/section', 'SeoController@sectionData');
    Route::resource('seo', 'SeoController');
    Route::get('post/{id}/comments', 'PostController@comments')->name('post.comments');
    Route::resource('post', 'PostController');
    Route::get('comment/{id}', 'PostController@comment')->name('comment.show');
    Route::delete('comment/{id}', 'PostController@commentDelete')->name('comment.destroy');

    Route::get('newsletter/{id}/send', 'NewsletterController@send');
    Route::get('newsletter/{id}/preview', 'NewsletterController@preview');
    Route::resource('newsletter', 'NewsletterController');

    Route::group(['prefix' => 'us'], function () {
        Route::get('/enterprise', 'UsController@enterprise')->name('us.enterprise');
        Route::get('/mission', 'UsController@mission')->name('us.mission');
        Route::get('/vision', 'UsController@vision')->name('us.vision');
        Route::get('/holding', 'UsController@holding')->name('us.holding');
        Route::get('/policy', 'UsController@policy')->name('us.policy');
        Route::get('/history', 'UsController@history')->name('us.history');
        Route::post('/enterprise', 'UsController@storeEnterprise');
        Route::post('/holding', 'UsController@storeHolding');
        Route::post('/{type}', 'UsController@store')->name('us.store');
    });

    //Routes to Galleries
    Route::post('/gallery/{id}/update', 'GalleryController@update')->name('gallery.update');
    Route::post('/gallery/{type}', 'GalleryController@uploadImagesByType');
    Route::delete('/gallery/{type}/{id}', 'GalleryController@deleteByType');
    Route::post('/pdf/{type}', 'GalleryController@uploadPDFByType');

    //Routes to Images
    Route::post('images/uploader', 'ImageController@postUploader')->name('images.uploader');
});

routes/front.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontController@index')->name('front.home');
Route::get('about', 'FrontController@about')->name('front.about');
Route::get('contact', 'FrontController@contact')->name('front.contact');
Route::get('events', 'FrontController@events')->name('front.events');
Route::get('event-detail', 'FrontController@event_detail')->name('front.event_detail');
Route::get('services', 'FrontController@services')->name('front.services');
Route::get('products', 'FrontController@products')->name('front.products');
Route::get('product-detail', 'FrontController@product_detail')->name('front.product_detail');
Route::get('product-filter', 'FrontController@product_filter')->name('front.product_filter');
Route::get('category', 'FrontController@category')->name('front.category');
Route::get('error-404', 'FrontController@error_404')->name('front.error_404');
Route::get('politics', 'FrontController@politics')->name('front.politics');
Route::get('certifications', 'FrontController@certifications')->name('front.certifications');
Route::get('search', 'FrontController@search')->name('front.search');
Route::get('no-product', 'FrontController@no_product')->name('front.no_product');
Route::get('thanks', 'FrontController@thanks')->name('front.thanks');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('chat/download', 'Admin\ChatController@download')->name('chat.download');

Route::namespace('Web')->group(function () {
    Route::get('/proximamente', 'WebController@coming')->name('web.coming');

    Route::get('/', 'WebController@index')->name('web.home');
    Route::get('nosotros', 'WebController@about')->name('web.about');
    Route::get('contacto', 'ContactController@index')->name('web.contact');

    Route::get('contacto/gracias', 'WebController@thanks')->name('web.contact.thanks');
    Route::get('eventos', 'WebController@events')->name('web.events.index');
    Route::post('eventos/loadmore', 'WebController@event_ajax')->name('web.events.load');
    Route::get('evento/{slug}', 'WebController@eventDetail')->name('web.events.show');
    Route::get('servicios', 'WebController@services')->name('web.services.index');
    Route::get('productos', 'ProductController@index')->name('web.products');
    Route::get('producto/buscar', 'WebController@product_filter')->name('web.product_filter');
    Route::get('producto/{slug?}', 'WebController@product_detail')->name('web.product_detail');
    Route::get('categoria', 'WebController@category')->name('web.category');
    Route::get('politicas', 'WebController@politics')->name('web.politics');
    Route::get('historia', 'WebController@history')->name('web.history');
    Route::get('certificaciones', 'WebController@certifications')->name('web.certifications');
    Route::post('category-products', 'ProductController@moreProductForCategory');
    Route::get('blogs', 'WebController@posts')->name('web.posts');
    Route::get('blog/{slug}', 'WebController@post')->name('web.post');
    Route::post('comment/{post}', 'CommentController@store')->name('web.comment.store');
    Route::post('more-comment', 'CommentController@more')->name('web.comment.more');
});


Route::post('/login', 'Auth\LoginController@login')->name('login.verify');
Route::group(['middleware' => 'auth'], function () {
    Route::get('/logout', 'Auth\LoginController@logout');
});

Route::get('newsletter', function () {
    $data['newsletter'] = \App\Models\Newsletter::find(1);
    return view('mailings.newsletter', $data);
});

app/Http/Controllers/Admin/SecondSliderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\Admin\SecondSliderRequest;
use App\Models\SubTable;
use Illuminate\Http\Request;

class SecondSliderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = [
            'text_center' => SubTable::getSecondBannerCenter(),
            'text_right' => SubTable::getSecondBannerRight(),
            'text_left' => SubTable::getSecondBannerLeft(),
        ];
        return view('admin.views.second-slider.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(SecondSliderRequest $request)
    {
        try {
            SubTable::updateOrCreate(['meta_key' => 'second_slider_center'], ['meta_key' => 'second_slider_center', 'meta_value' => $request->text_center]);
            SubTable::updateOrCreate(['meta_key' => 'second_slider_right'], ['meta_key' => 'second_slider_right', 'meta_value' => $request->text_right, 'meta_option' => $request->link_right]);
            SubTable::updateOrCreate(['meta_key' => 'second_slider_left'], ['meta_key' => 'second_slider_left', 'meta_value' => $request->text_left, 'meta_option' => $request->link_left]);
            $response = $this->responseSuccess('Banner Actualizado', ['redirect' => route('second-slider.index')]);
        } catch (\Exception $e) {
            $response = $this->responseError($e->getMessage());
        }
        return $response;
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/views/second-slider/index.blade.php
@extends('admin.layout.base')

@section('bodyId')id="slider"@endsection

@section('content')
    <section class="wrapper">
        <form action="{{ route('second-slider.store') }}" method="POST">
            {{ csrf_field() }}
            <div class="row">
                <div class="col-sm-12">
                    <div class="panel">
                        <header class="panel-heading">Editar Banner Secundario</header>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-8">
                    <div class="panel">
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="row">
                                        <div class="col-xs-12 col-md-12">
                                            <div class="form-group">
                                                <label>Texto central</label>
                                                <input class="form-control m-bot15" type="text" name="text_center"
                                                       value="{{ isset($text_center) ? $text_center->meta_value : ''}}">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-xs-6">
                                            <div class="form-group">
                                                <label>Texto izquierda</label>
                                                <input class="form-control m-bot15" type="text" name="text_left"
                                                       value="{{ isset($text_left) ? $text_left->meta_value : ''}}">
                                            </div>
                                        </div>
                                        <div class="col-xs-6">
                                            <div class="form-group">
                                                <label>Link izquierda</label>
                                                <input class="form-control m-bot15" type="text" name="link_left"
                                                       value="{{ isset($text_left) ? $text_left->meta_option : ''}}"
                                                       placeholder="http://..">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-xs-6">
                                            <div class="form-group">
                                                <label>Texto derecha</label>
                                                <input class="form-control m-bot15" type="text" name="text_right"
                                                       value="{{ isset($text_right) ? $text_right->meta_value : ''}}">
                                            </div>
                                        </div>
                                        <div class="col-xs-6">
                                            <div class="form-group">
                                                <label>Link derecha</label>
                                                <input class="form-control m-bot15" type="text" name="link_right"
                                                       value="{{ isset($text_right) ? $text_right->meta_option : ''}}"
                                                       placeholder="http://..">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-sm-4">
                    <div class="panel">
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="row">
                                        <div class="col-xs-6">
                                            <a href="{{ route('admin.alliance') }}"
                                               class="btn btn-danger btn-block">Cancelar</a>
                                        </div>
                                        <div class="col-xs-6">
                                            <button class="btn btn-success btn-block">Guardar</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </form>
    </section>
@endsection

@section('js')
    <script type="text/javascript" src="{{ asset('js/vendor/ckeditor/ckeditor.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/vendor/toastr.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/scripts/form.js') }}"></script>
    <script>
        Form.form('form');
    </script>
@endsection