routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'guest'], function () {
    Route::get('/', 'AdminController@login')->name('login');
});
Route::group(['middleware' => 'auth'], function () {
    Route::group(['prefix' => 'home'], function () {
        Route::get('/', 'AdminController@index')->name('admin.home');
        Route::get('/alliance', 'AdminController@alliance')->name('admin.alliance');
        Route::get('/footer', 'AdminController@footer')->name('admin.footer');
        Route::get('/event', 'AdminController@event')->name('event.banner');
        Route::get('/service', 'AdminController@service')->name('service.banner');
        Route::get('/header', 'AdminController@header')->name('admin.header');
        Route::get('/descriptive', 'AdminController@descriptive')->name('admin.descriptive');
        Route::post('/header', 'AdminController@postHeader')->name('admin.header.store');
        Route::post('/footer', 'AdminController@postFooter');
        Route::post('/event', 'AdminController@postEvent');
        Route::post('/service', 'AdminController@postService');
        Route::post('/descriptive', 'AdminController@postDescriptive')->name('admin.descriptive.store');
    });

    Route::group(['prefix' => 'table'], function () {
        Route::get('brand', 'BrandController@getList');
        Route::get('category', 'CategoryController@getList');
        Route::get('certificate', 'CertificateController@getList');
        Route::get('corporation', 'CorporationController@getList');
        Route::get('event', 'EventController@getList');
        Route::get('headquarter', 'HeadquarterController@getList');
        Route::get('how-contact', 'HowContactController@getList');
        Route::get('type', 'ProductTypeController@getList');
        Route::get('product', 'ProductController@getList');
        Route::get('service', 'ServiceController@getList');
        Route::get('slider', 'SliderController@getList');
        Route::get('specialization', 'SpecializationController@getList');
        Route::get('seo', 'SeoController@listData');
        Route::get('post', 'PostController@listData');
        Route::get('newsletter', 'NewsletterController@listData');
    });

    Route::group(['prefix' => 'reorder'], function () {
        Route::post('brand', 'BrandController@reorder');
        Route::post('category', 'CategoryController@reorder');
        Route::post('certificate', 'CertificateController@reorder');
        Route::post('corporation', 'CorporationController@reorder');
        Route::post('event', 'EventController@reorder');
        Route::post('headquarter', 'HeadquarterController@reorder');
        Route::post('how-contact', 'HowContactController@reorder');
        Route::post('type', 'ProductTypeController@reorder');
        Route::post('product', 'ProductController@reorder');
        Route::post('service', 'ServiceController@reorder');
        Route::post('slider', 'SliderController@reorder');
        Route::post('specialization', 'SpecializationController@reorder');
        Route::post('post', 'PostController@reorder');
    });


    Route::resource('brand', 'BrandController');
    Route::resource('category', 'CategoryController');
    Route::resource('certificate', 'CertificateController');
    Route::resource('corporation', 'CorporationController');
    Route::get('contact/download', 'ContactController@download')->name('contact.download');
    Route::resource('contact', 'ContactController');
    Route::resource('event', 'EventController');
    Route::resource('how-contact', 'HowContactController');
    Route::resource('product/detail', 'ProductDetailController');
    Route::resource('product/type', 'ProductTypeController');
    Route::resource('product', 'ProductController');
    Route::resource('profile', 'ProfileController');
    Route::resource('role', 'RoleController');
    Route::resource('service', 'ServiceController');
    Route::resource('second-slider', 'SecondSliderController');
    Route::post('slider/text-general', 'SliderController@textGeneralUpdate')->name('slider.text.general');
    Route::resource('slider', 'SliderController');
    Route::resource('specialization', 'SpecializationController');
    Route::resource('headquarter', 'HeadquarterController');
    Route::resource('user', 'UserController');
    Route::get('seo/section', 'SeoController@sectionData');
    Route::resource('seo', 'SeoController');
    Route::get('post/{id}/comments', 'PostController@comments')->name('post.comments');
    Route::resource('post', 'PostController');
    Route::get('comment/{id}', 'PostController@comment')->name('comment.show');
    Route::delete('comment/{id}', 'PostController@commentDelete')->name('comment.destroy');

    Route::get('newsletter/{id}/send', 'NewsletterController@send');
    Route::get('newsletter/{id}/preview', 'NewsletterController@preview');
    Route::resource('newsletter', 'NewsletterController');

    Route::group(['prefix' => 'us'], function () {
        Route::get('/enterprise', 'UsController@enterprise')->name('us.enterprise');
        Route::get('/mission', 'UsController@mission')->name('us.mission');
        Route::get('/vision', 'UsController@vision')->name('us.vision');
        Route::get('/holding', 'UsController@holding')->name('us.holding');
        Route::get('/policy', 'UsController@policy')->name('us.policy');
        Route::get('/history', 'UsController@history')->name('us.history');
        Route::post('/enterprise', 'UsController@storeEnterprise');
        Route::post('/holding', 'UsController@storeHolding');
        Route::post('/{type}', 'UsController@store')->name('us.store');
    });

    //Routes to Galleries
    Route::post('/gallery/{id}/update', 'GalleryController@update')->name('gallery.update');
    Route::post('/gallery/{type}', 'GalleryController@uploadImagesByType');
    Route::delete('/gallery/{type}/{id}', 'GalleryController@deleteByType');
    Route::post('/pdf/{type}', 'GalleryController@uploadPDFByType');

    //Routes to Images
    Route::post('images/uploader', 'ImageController@postUploader')->name('images.uploader');
});

routes/front.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontController@index')->name('front.home');
Route::get('about', 'FrontController@about')->name('front.about');
Route::get('contact', 'FrontController@contact')->name('front.contact');
Route::get('events', 'FrontController@events')->name('front.events');
Route::get('event-detail', 'FrontController@event_detail')->name('front.event_detail');
Route::get('services', 'FrontController@services')->name('front.services');
Route::get('products', 'FrontController@products')->name('front.products');
Route::get('product-detail', 'FrontController@product_detail')->name('front.product_detail');
Route::get('product-filter', 'FrontController@product_filter')->name('front.product_filter');
Route::get('category', 'FrontController@category')->name('front.category');
Route::get('error-404', 'FrontController@error_404')->name('front.error_404');
Route::get('politics', 'FrontController@politics')->name('front.politics');
Route::get('certifications', 'FrontController@certifications')->name('front.certifications');
Route::get('search', 'FrontController@search')->name('front.search');
Route::get('no-product', 'FrontController@no_product')->name('front.no_product');
Route::get('thanks', 'FrontController@thanks')->name('front.thanks');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('chat/download', 'Admin\ChatController@download')->name('chat.download');

Route::namespace('Web')->group(function () {
    Route::get('/proximamente', 'WebController@coming')->name('web.coming');

    Route::get('/', 'WebController@index')->name('web.home');
    Route::get('nosotros', 'WebController@about')->name('web.about');
    Route::get('contacto', 'ContactController@index')->name('web.contact');

    Route::get('contacto/gracias', 'WebController@thanks')->name('web.contact.thanks');
    Route::get('eventos', 'WebController@events')->name('web.events.index');
    Route::post('eventos/loadmore', 'WebController@event_ajax')->name('web.events.load');
    Route::get('evento/{slug}', 'WebController@eventDetail')->name('web.events.show');
    Route::get('servicios', 'WebController@services')->name('web.services.index');
    Route::get('productos', 'ProductController@index')->name('web.products');
    Route::get('producto/buscar', 'WebController@product_filter')->name('web.product_filter');
    Route::get('producto/{slug?}', 'WebController@product_detail')->name('web.product_detail');
    Route::get('categoria', 'WebController@category')->name('web.category');
    Route::get('politicas', 'WebController@politics')->name('web.politics');
    Route::get('historia', 'WebController@history')->name('web.history');
    Route::get('certificaciones', 'WebController@certifications')->name('web.certifications');
    Route::post('category-products', 'ProductController@moreProductForCategory');
    Route::get('blogs', 'WebController@posts')->name('web.posts');
    Route::get('blog/{slug}', 'WebController@post')->name('web.post');
    Route::post('comment/{post}', 'CommentController@store')->name('web.comment.store');
    Route::post('more-comment', 'CommentController@more')->name('web.comment.more');
});


Route::post('/login', 'Auth\LoginController@login')->name('login.verify');
Route::group(['middleware' => 'auth'], function () {
    Route::get('/logout', 'Auth\LoginController@logout');
});

Route::get('newsletter', function () {
    $data['newsletter'] = \App\Models\Newsletter::find(1);
    return view('mailings.newsletter', $data);
});

app/Models/Gallery.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\File;

class Gallery extends Model
{
    use SoftDeletes;
    public $timestamps = true;
    protected $table = 'galleries';
    protected $hidden = ['created_at', 'updated_at', 'deleted_at'];
    protected $dates = ['created_at', 'updated_at', 'deleted_at'];
    protected $fillable = ['name', 'type', 'mime', 'description', 'path'];

    /**
     * @param $bytes
     * @return string
     */
    private static function bytesToHuman($bytes)
    {
        $units = ['B', 'KiB', 'MiB', 'GiB', 'TiB', 'PiB'];
        for ($i = 0; $bytes > 1024; $i++) {
            $bytes /= 1024;
        }
        return round($bytes, 2) . ' ' . $units[$i];
    }

    /**
     * @return \Illuminate\Contracts\Routing\UrlGenerator|string
     */
    public function getThumbnailAttribute()
    {
        return url(str_replace(File::name('storage/' . $this->path) . '.' . File::extension('storage/' . $this->path), File::name('storage/' . $this->path) . '_80x80.' . File::extension('storage/' . $this->path), $this->path));
    }

    /**
     * @return string
     */
    public function getThumbnailSrcAttribute()
    {
        return public_path(str_replace(File::name($this->path) . '.' . File::extension($this->path), File::name($this->path) . '_80x80.' . File::extension($this->path), $this->path));
    }

    /**
     * @return string
     */
    public function getSizeAttribute()
    {
        return self::bytesToHuman(File::size($this->path));
    }

    /**
     * @return mixed
     */
    public function getMimetypeAttribute()
    {
        return File::mimeType($this->path);
    }

    /**
     * @return \Illuminate\Contracts\Routing\UrlGenerator|string
     */
    public function getUrlAttribute()
    {
        return url($this->path);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function product()
    {
        return $this->belongsTo('App\Models\Product');
    }

    public static function getAlliances()
    {
        return Gallery::where('type', '=', 'ALLIANCE')->get();
    }
}

resources/views/admin/partials/aside.blade.php
<!--sidebar start-->
<aside>
    <div id="sidebar" class="nav-collapse ">
        <!-- sidebar menu start-->
        <ul class="sidebar-menu" id="nav-accordion">
            @can('manage_general')
                <li class="sub-menu">
                    <a href="javascript:void(0)"
                       class="{{ Route::is('admin.*', 'slider.*','certificate.*', 'second-slider.*') ? 'active' : '' }}">
                        <i class="fa fa-caret-right"></i><span>Generales</span>
                    </a>
                    <ul class="sub">
                        <li class="{{ Route::is('admin.alliance') ? 'active' : '' }}">
                            <a href="{{ route('admin.alliance') }}">Aliados</a>
                        </li>
                        <li class="{{ Route::is('admin.header') ? 'active' : '' }}">
                            <a href="{{ route('admin.header') }}">Header</a>
                        </li>
                        <li class="{{ Route::is('slider.*') ? 'active' : '' }}">
                            <a href="{{ route('slider.index') }}">Banner Principal</a>
                        </li>
                        <li class="{{ Route::is('second-slider.*') ? 'active' : '' }}">
                            <a href="{{ route('second-slider.index') }}">Banner Secundario</a>
                        </li>
                        <li class="{{ Route::is('admin.descriptive') ? 'active' : '' }}">
                            <a href="{{ route('admin.descriptive') }}">Nuestras Líneas</a>
                        </li>
                        <li class="{{ Route::is('certificate.*') ? 'active' : '' }}">
                            <a href="{{ route('certificate.index') }}">Certificados</a>
                        </li>
                        <li class="{{ Route::is('admin.footer') ? 'active' : '' }}">
                            <a href="{{ route('admin.footer') }}">Footer</a>
                        </li>
                    </ul>
                </li>
            @endcan
            @can('manage_us')
                <li class="sub-menu">
                    <a href="javascript:void(0)"
                       class="{{ Route::is('us.*', 'headquarter.*', 'corporation.*') ? 'active' : '' }}">
                        <i class="fa fa-caret-right"></i><span>Nosotros</span>
                    </a>
                    <ul class="sub">
                        <li class="{{ Route::is('us.enterprise') ? 'active' : '' }}">
                            <a href="{{ route('us.enterprise') }}">Empresa</a>
                        </li>
                        <li class="{{ Route::is('us.mission') ? 'active' : '' }}">
                            <a href="{{ route('us.mission') }}">Misión</a>
                        </li>
                        <li class="{{ Route::is('us.vision') ? 'active' : '' }}">
                            <a href="{{ route('us.vision') }}">Visión</a>
                        </li>
                        <li class="{{ Route::is('us.holding') ? 'active' : '' }}">
                            <a href="{{ route('us.holding') }}">Valores</a>
                        </li>
                        <li class="{{ Route::is('us.policy') ? 'active' : '' }}">
                            <a href="{{ route('us.policy') }}">Politicas</a>
                        </li>
                        <li class="{{ Route::is('us.history') ? 'active' : '' }}">
                            <a href="{{ route('us.history') }}">Historia</a>
                        </li>
                        <li class="{{ Route::is('headquarter.*') ? 'active' : '' }}">
                            <a href="{{ route('headquarter.index') }}">Sedes</a>
                        </li>
                        <li class="{{ Route::is('corporation.*') ? 'active' : '' }}">
                            <a href="{{ route('corporation.index') }}">Corporaciones</a>
                        </li>
                    </ul>
                </li>
            @endcan
            @can('manage_category')
                <li>
                    <a href="{{ route('category.index') }}" class="{{ Route::is('category.index') ? 'active' : '' }}">
                        <i class="fa fa-caret-right"></i><span>Categorias</span>
                    </a>
                </li>
            @endcan
            @can('manage_product')
                <li class="sub-menu">
                    <a href="javascript:void(0)"
                       class="{{ Route::is('product.*', 'brand.*', 'type.*') ? 'active' : '' }}">
                        <i class="fa fa-caret-right"></i><span>Productos</span>
                    </a>
                    <ul class="sub">
                        <li class="{{ Route::is('product.*') ? 'active' : '' }}">
                            <a href="{{ route('product.index') }}">Listado</a>
                        </li>
                        <li class="{{ Route::is('brand.*') ? 'active' : '' }}">
                            <a href="{{ route('brand.index') }}">Marcas</a>
                        </li>
                        <li class="{{ Route::is('type.*') ? 'active' : '' }}">
                            <a href="{{ route('type.index') }}">Tipos</a>
                        </li>
                    </ul>
                </li>
            @endcan
            @can('manage_service')
                <li class="sub-menu">
                    <a href="javascript:void(0)" class="{{ Route::is('service.*') ? 'active' : '' }}">
                        <i class="fa fa-caret-right"></i><span>Servicios</span>
                    </a>
                    <ul class="sub">
                        <li class="{{ Route::is('service.index', 'service.create', 'service.edit') ? 'active' : '' }}">
                            <a href="{{ route('service.index') }}">Listado</a>
                        </li>
                        <li class="{{ Route::is('service.banner') ? 'active' : '' }}">
                            <a href="{{ route('service.banner') }}">Encabezado</a>
                        </li>
                    </ul>
                </li>
            @endcan
            @can('manage_event')
                <li class="sub-menu">
                    <a href="javascript:void(0)" class="{{ Route::is('event.*') ? 'active' : '' }}">
                        <i class="fa fa-caret-right"></i><span>Eventos</span>
                    </a>
                    <ul class="sub">
                        <li class="{{ Route::is('event.index', 'event.create', 'event.edit') ? 'active' : '' }}">
                            <a href="{{ route('event.index') }}">Listado</a>
                        </li>
                        <li class="{{ Route::is('event.banner') ? 'active' : '' }}">
                            <a href="{{ route('event.banner') }}">Encabezado</a>
                        </li>
                    </ul>
                </li>
            @endcan
            @can('manage_specialization')
                <li>
                    <a href="{{ route('specialization.index') }}"
                       class="{{ Route::is('specialization.*') ? 'active' : '' }}">
                        <i class="fa fa-caret-right"></i><span>Nivel de Usuarios</span>
                    </a>
                </li>
            @endcan
            @can('manage_how_contact')
                <li>
                    <a href="{{ route('how-contact.index') }}" class="{{ Route::is('how-contact.*') ? 'active' : '' }}">
                        <i class="fa fa-caret-right"></i><span>Medios de contacto</span>
                    </a>
                </li>
            @endcan
            @can('manage_message')
                <li>
                    <a href="{{ route('contact.index') }}" class="{{ Route::is('contact.*') ? 'active' : '' }}">
                        <i class="fa fa-caret-right"></i><span>Mensajes</span>
                    </a>
                </li>
            @endcan
            @can('manage_users')
                <li class="sub-menu">
                    <a href="javascript:void(0)" class="{{ Route::is('user.*', 'role.*') ? 'active' : '' }}">
                        <i class="fa fa-caret-right"></i><span>Usuarios</span>
                    </a>
                    <ul class="sub">
                        <li class="{{ Route::is('user.*') ? 'active' : '' }}">
                            <a href="{{ route('user.index') }}">Listado</a>
                        </li>
                        <li class="{{ Route::is('role.*') ? 'active' : '' }}">
                            <a href="{{ route('role.index') }}">Roles</a>
                        </li>
                    </ul>
                </li>
            @endcan
            <li>
                <a href="{{ route('post.index') }}" class="{{ Route::is('post.*') ? 'active' : '' }}">
                    <i class="fa fa-caret-right"></i><span>Blog</span>
                </a>
            </li>
            <li>
                <a href="{{ route('newsletter.index') }}" class="{{ Route::is('newsletter.*') ? 'active' : '' }}">
                    <i class="fa fa-caret-right"></i><span>Newsletter</span>
                </a>
            </li>
            <li>
                <a href="{{ route('seo.index') }}" class="{{ Route::is('seo.*') ? 'active' : '' }}">
                    <i class="fa fa-caret-right"></i><span>SEO</span>
                </a>
            </li>
        </ul>
        <!-- sidebar menu end-->
    </div>
</aside>
<!--sidebar end-->

resources/views/admin/partials/footer.blade.php
<!--footer start-->
<footer class="site-footer">
    <div class="text-center">
        {{ date('Y') }} &copy; GRUPO BONNETT Powered by WHIZ
        <a href="#" class="go-top"><i class="fa fa-angle-up"></i></a>
    </div>
</footer>
<!--footer end-->

resources/views/admin/partials/header.blade.php
<!--header start-->
<header class="header white-bg">
    <div class="sidebar-toggle-box">
        <i class="fa fa-bars"></i>
    </div>
    <!--logo start-->
    {{--<a href="/admin" class="logo">Bon<span>nett</span></a>--}}
    <a href="/admin" class="logo"><img src="{{ asset('img/admin/logo.png') }}" alt="" height="48"></a>
    <!--logo end-->
    <div class="top-nav ">
        <!--search & user info start-->
        <ul class="nav pull-right top-menu">
        {{--<li>--}}
        {{--<input type="text" class="form-control search" placeholder="Buscar">--}}
        {{--</li>--}}
        <!-- user login dropdown start-->
            <li class="dropdown">
                <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                    <img alt="" src="{{ asset(isset(Auth::user()->image)? Auth::user()->image->path: 'img/admin/user.png') }}"
                         width="29px" height="29px"
                         style="padding: 2px">
                    <span class="username">{{ Auth::user()->name }}</span>
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu extended logout" style="width: 160px!important;">
                    <div class="log-arrow-up"></div>
                    <li>
                        <a href="{{ route('profile.index') }}" class="btn-info"><i class="fa fa-user"></i> Profile</a>
                    </li>
                    <li>
                        <a href="{{ url('/logout') }}" class="btn-warning"><i class="fa fa-key"></i> Log Out</a>
                    </li>
                </ul>
            </li>
            <!-- user login dropdown end -->
        </ul>
        <!--search & user info end-->
    </div>
</header>
<!--header end-->

resources/views/admin/partials/message.blade.php
<div class="panel" style="background-color: #002347; color: #fff">
    <header class="panel-body">
        Para poder cargar la galería de fotos, primero debes asignar una imagen de portada.
        Recuerda editar la imagen de portada a la medida adecuada haciendo clic en "editar".
    </header>
</div>

resources/views/admin/partials/upload-gallery-alliance.blade.php
<form action="" id="{{ empty($id)?'fileupload':$id }}">
    <div class="row">
        <div class="col-md-12">
            <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
            <div class="row fileupload-buttonbar">
                <div class="col-lg-12">
                    <!-- The fileinput-button span is used to style the file input field as button -->
                    <span class="btn btn-success fileinput-button">
                        <i class="glyphicon glyphicon-plus"></i>
                        <span>Agregar archivos...</span>
                        <input type="file" name="gallery[]" multiple>
                    </span>
                    <button type="submit" class="btn btn-primary start">
                        <i class="glyphicon glyphicon-upload"></i>
                        <span>Subir</span>
                    </button>
                    <button type="reset" class="btn btn-warning cancel">
                        <i class="glyphicon glyphicon-ban-circle"></i>
                        <span>Cancelar</span>
                    </button>
                    <button type="button" class="btn btn-danger delete">
                        <i class="glyphicon glyphicon-trash"></i>
                        <span>Eliminar</span>
                    </button>
                    <input type="checkbox" class="toggle">
                    <!-- The global file processing state -->
                    <span class="fileupload-process"></span>
                </div>
                <!-- The global progress state -->
                <div class="col-lg-12 fileupload-progress fade">
                    <!-- The global progress bar -->
                    <div class="progress progress-striped active" role="progressbar" aria-valuemin="0"
                         aria-valuemax="100">
                        <div class="progress-bar progress-bar-success" style="width:0%;"></div>
                    </div>
                    <!-- The extended global progress state -->
                    <div class="progress-extended">&nbsp</div>
                </div>
            </div>
            <!-- The table listing the files available for upload/download -->
            <table role="presentation" class="table table-striped">
                <tbody class="files">
                @foreach($gallery as $file)
                    @if(file_exists($file->path))
                        <tr class="template-download fade in">
                            <td>
                                <span class="preview">
                                    @if ($file->thumbnail && $is_image)
                                        <a href="{{ url($file->path) }}" title="" download="" data-gallery>
                                            <img src="{{ $file->thumbnail }}"></a>
                                    @endif
                                </span>
                            </td>
                            <td style="vertical-align: middle">
                                <p class="name">
                                    <a href="{{ url($file->path) }}" title="{{ $file->name }}"
                                       download="{{ $file->name }}" data-gallery> {{ $file->name }}</a>
                                </p>
                            </td>
                            <td style="vertical-align: middle">
                                <p class="name">
                                    <input type="text" class="form-control" placeholder="Link" name="description"
                                           value="{{ $file->description }}">
                                </p>
                            </td>
                            <td style="vertical-align: middle"><span class="size">{{ $file->size }}</span></td>
                            <td style="vertical-align: middle; text-align: right">
                                <button type="button" class="btn btn-warning edit"
                                        data-url="{{ route('gallery.update', ['id'=> $file->id]) }}">
                                    <i class="glyphicon glyphicon-pencil"></i><span>Editar</span>
                                </button>
                                <button class="btn btn-danger delete" data-type="DELETE"
                                        data-url="{{ url('/admin/gallery/'.$type.'/'.$file->id) }}">
                                    <i class="glyphicon glyphicon-trash"></i><span>Eliminar</span>
                                </button>
                                <input type="checkbox" name="delete" value="1" class="toggle">
                            </td>
                        </tr>
                    @endif
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
</form>

resources/views/admin/partials/upload-image.blade.php
<span id="{{ $inputName }}" class="popover-validate">{{ $title }}</span>
<div class="fileupload fileupload-new" data-provides="fileupload">
    <div class="fileupload-new thumbnail" style="width: 100%; height: 150px;">
        @if(isset($path))
            <img src="{{ url($path) }}" alt=""/>
        @else
            {{--<img src="{{ asset ('img/team/default.png') }}" alt="" style="width: 150px; height: 140px;"/>--}}
        @endif
    </div>
    <div class="fileupload-preview fileupload-exists thumbnail"
         style="width: 100%; max-height: 150px; line-height: 20px;">
    </div>
    <div class="text-center">
        <span class="btn btn-white btn-file">
            <span class="fileupload-new"><i class="fa fa-paper-clip"></i> Seleccionar imagen</span>
            <span class="fileupload-exists"><i class="fa fa-undo"></i> Cambiar imagen</span>
            <input type="file" class="default"/>
        </span>
        <a href="#" class="btn btn-danger fileupload-exists" data-dismiss="fileupload">
            <i class="fa fa-trash"></i> Eliminar
        </a>
        <button type="button" id="cropper_up" class="btn btn-warning fileupload-exists" data-toggle="modal"
                data-target="#cropper_modal" style="margin-top: 3px"><i class="fa fa-edit"></i> Editar
        </button>
    </div>
</div>